### ISSUE TITLE
what does 'go into dev/shadow.clj, load the file' means?

### ISSUE THREAD

**Issue by happy15** [den1k/zeal#2]
Hello, clojure noob here, i cannot follow your instructions :(

**Comment by sooheon** [comment]
This means the entrypoint for the app is that `(mount/start)` call. [Mount](https://github.com/tolitius/mount) uses Clojure's dependency resolution to resolve component graph for `defstates` (which you can see sprinkled around the codebase). `mount/start` starts each of these stateful components and manages them for you so you can stop/restart.

Start a [repl](https://clojure.org/guides/repl/introduction), load the shadow.clj namespace, and call `(mount/start)`.

**Comment by den1k** [comment]
Thanks @sooheon. Yeah @happy15 it's not very user friendly at the moment. The idea that you start up a clojure repl. Then go into dev/shadow.clj, load the file and lastly call (mount/start). This will start compiling clojurescript + a server and local database.

If this is too difficult, stay tuned. I'm working on making this easier in the coming weeks.

**Comment by happy15** [comment]
thanks @sooheon @den1k for reply. looking forward to that.
