### ISSUE TITLE
Reason for uix dependency being local, rather than git sha?

### ISSUE THREAD

**Issue by sooheon** [den1k/zeal#3]
I see there are local deps for uix.core and uix.dom, is there any problem with replacing these with the latest uix commits?

**Comment by den1k** [comment]
I think I was hacking around in uix at the beginning but the current version should be fine. Will swap dep w/ git coords.

**Comment by den1k** [comment]
@sooheon I realized why I used local deps. UIX contains multiple articles under one git/url. They are core, dom & rn. All in one repo. This currently doesn't work with deps.

**Comment by den1k** [comment]
@sooheon found a solution. this is fixed now.
