### ISSUE TITLE
Syntax error (IllegalStateException) while loading zeal.ui.talk/device-meta

### ISSUE THREAD

**Issue by sooheon** [den1k/zeal#4]
Clojure complains that `var: #'kitchen-async.promise/with-error-handling is not public`. That fn is in p/let macroexpansion. Have you not had this issue developing locally?

**Comment by den1k** [comment]
Hey @sooheon, yes and I've resolved this by wrapping it for in a reader conditional for cljs. Thanks for the feedback. Pushing those changes soon.
